name: CI
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # - name: Update theme
      #   run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.pages }}
          external_repository: 3manuek/3manuek.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: 3manuek
          user_email: 3manuek@gmail.com
          publish_branch: main
        #   cname: example.com